name: chat_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <3.4.0'  # 👈 3.4.0 dan yuqoriga o‘tmaydi

dependencies:
  shelf: ^1.3.1          # 👈 Versiyani 1.3.1 ga tushiring
  shelf_web_socket: ^2.0.0
