name: chat_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <3.4.0'  # 👈 3.4.0 dan yuqoriga o‘tmaydi

dependencies:
  shelf: ^1.3.1          # 👈 Versiyani 1.3.1 ga tushiring
  shelf_web_socket: ^2.0.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
