name: chat_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <3.1.0'  # Railway Dart SDK: 3.0.6

dependencies:
  shelf: ^1.3.1
  shelf_web_socket: ^1.0.1  # 👉 AYNAN SHU VERSIYA
